version: '3.9'

services:
  mongodb:
    image: mongo:5.0.5
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
      - ./init-mongodb:/docker-entrypoint-initdb.d
      - ./init-mongodb/data/:/tmp/data